version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloaded_images:/app/downloaded_images
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  downloaded_images:
